# -*- coding: utf-8 -*-
"""guardiao_mvp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UMilP16Cu55t7rzGZnyH_YaHQ-hlbuRz

# 🐢 Guardião das Tartaruguinhas: Monitoramento Comunitário de Ninhos

---

**Desenvolvido por:** Eric Narciso Pimentel dos Santos

**Curso:** Inteligência Artificial Aplicada aos Desafios Socioambientais da Amazônia

**Instituição:** I2A2 - Instituto de Inteligência Artificial Aplicada

**Data:** 28/07/2025

---

## 1. Contexto do Projeto

Em uma comunidade ribeirinha no coração da Amazônia, um esforço coletivo e inspirador de conservação dos quelônios ganha vida. Liderado por professores e jovens voluntários, o projeto **Guardião das Tartaruguinhas** visa monitorar os ninhos de tartarugas para garantir que o maior número possível de filhotes chegue com segurança ao rio, fortalecendo o ciclo de preservação e a cultura local.

## 2. O Desafio

Os dados dos ninhos — como localização, quantidade de ovos, status e riscos — eram registrados manualmente em papel. Essa metodologia, embora nobre, resultava em informações desorganizadas, inconsistentes e de difícil análise. Responder a perguntas essenciais para a tomada de decisão, como "Qual a média de ovos?" ou "Qual região apresenta maior risco?", tornava-se uma tarefa árdua e imprecisa.

## 3. A Solução Proposta

Este notebook representa a solução tecnológica para o desafio. Trata-se de um sistema simples, porém robusto, desenvolvido em Python para permitir que os voluntários da comunidade possam:

* **Registrar** os dados dos ninhos de forma padronizada.
* **Validar** as informações no momento da entrada para garantir sua integridade.
* **Analisar** os dados acumulados para gerar estatísticas e insights acionáveis.
* **Apoiar** a tomada de decisão semanal do grupo de proteção, otimizando os esforços de conservação.


## Nosso desafio não é apenas contar os ovos. É usar cada número, cada dado, para tecer uma rede de proteção em torno da vida. Aqui, cada linha de código é um ato de esperança.




Este projeto é a ponte entre o conhecimento tradicional e a tecnologia acessível, transformando dados em um escudo para a biodiversidade amazônica.
"""

# =============================================================================
# TAREFA INDIVIDUAL V: Guardião das Tartaruguinhas (MVP)
#
# NOME DO ALUNO: Eric Narciso Pimentel dos Santos
# CURSO: Inteligência Artificial Aplicada aos Desafios Socioambientais da Amazônia
# INSTITUTO: I2A2 - Instituto de Inteligência Artificial Aplicada
# DATA: 28/07/2025
# VERSÃO: 2.0 - Validação Robusta e Regras de Negócio
# =============================================================================

# -----------------------------------------------------------------------------
# FASE 0: CONSTANTES E REGRAS DE NEGÓCIO
# -----------------------------------------------------------------------------
# Para garantir a integridade dos dados, definimos limites realistas
# baseados no conhecimento de domínio (biologia dos quelônios).
OVOS_MIN_REALISTA = 5
OVOS_MAX_REALISTA = 200
DIAS_ECLOSAO_MIN = 1
DIAS_ECLOSAO_MAX = 130

# -----------------------------------------------------------------------------
# FASE 1: ESTRUTURA DE DADOS E CARGA INICIAL
# -----------------------------------------------------------------------------
# Base de dados inicial com 10 registros, usando os emojis corretos (🟢, 🟡, 🔴).
ninhos = [
    {"regiao": "Praia Norte", "quantidade_ovos": 102, "status": "intacto", "risco": "🟢", "dias_para_eclosao": 12, "predadores": False},
    {"regiao": "Praia Central", "quantidade_ovos": 89, "status": "danificado", "risco": "🔴", "dias_para_eclosao": 3, "predadores": True},
    {"regiao": "Praia Sul", "quantidade_ovos": 120, "status": "ameaçado", "risco": "🟡", "dias_para_eclosao": 7, "predadores": False},
    {"regiao": "Praia Central", "quantidade_ovos": 75, "status": "intacto", "risco": "🟢", "dias_para_eclosao": 2, "predadores": False},
    {"regiao": "Praia Norte", "quantidade_ovos": 60, "status": "danificado", "risco": "🔴", "dias_para_eclosao": 5, "predadores": True},
    {"regiao": "Praia Sul", "quantidade_ovos": 95, "status": "intacto", "risco": "🟢", "dias_para_eclosao": 20, "predadores": False},
    {"regiao": "Praia Norte", "quantidade_ovos": 110, "status": "ameaçado", "risco": "🟡", "dias_para_eclosao": 8, "predadores": True},
    {"regiao": "Praia Central", "quantidade_ovos": 81, "status": "ameaçado", "risco": "🟡", "dias_para_eclosao": 15, "predadores": False},
    {"regiao": "Praia Sul", "quantidade_ovos": 70, "status": "danificado", "risco": "🔴", "dias_para_eclosao": 1, "predadores": True},
    {"regiao": "Praia Norte", "quantidade_ovos": 130, "status": "intacto", "risco": "🟢", "dias_para_eclosao": 25, "predadores": False},
]

# -----------------------------------------------------------------------------
# FASE 2: FUNÇÕES DO SISTEMA
# -----------------------------------------------------------------------------

def exibir_relatorio_completo(base_de_ninhos):
    """Exibe um relatório formatado com os dados de todos os ninhos registrados."""
    print("\n" + "="*80)
    print("||" + " RELATÓRIO COMPLETO DE NINHOS ".center(76) + "||")
    print("="*80)

    if not base_de_ninhos:
        print("\nNenhum ninho registrado na base de dados.\n")
    else:
        print(f"| {'ID':<3} | {'REGIÃO':<15} | {'OVOS':<5} | {'STATUS':<12} | {'RISCO':<7} | {'ECLOSÃO (dias)':<16} | {'PREDADORES':<10} |")
        print("-" * 80)

        id_ninho = 1
        for ninho in base_de_ninhos:
            predadores_str = "Sim" if ninho["predadores"] else "Não"
            print(f"| {id_ninho:<3} | {ninho['regiao']:<15} | {ninho['quantidade_ovos']:<5} | {ninho['status']:<12} | {ninho['risco']:<7} | {ninho['dias_para_eclosao']:<16} | {predadores_str:<10} |")
            id_ninho = id_ninho + 1

    print("="*80)


def calcular_estatisticas(base_de_ninhos):
    """Calcula e exibe as estatísticas chave sobre os ninhos monitorados."""
    print("\n" + "="*80)
    print("||" + " ESTATÍSTICAS DE MONITORAMENTO ".center(76) + "||")
    print("="*80)

    if not base_de_ninhos:
        print("\nNenhum dado para análise.\n")
        print("="*80)
        return

    # 1. Total de ninhos
    total_ninhos = len(base_de_ninhos)
    print(f"\n[ 1 ] TOTAL DE NINHOS MONITORADOS: {total_ninhos}")

    # 2. Média de ovos em ninhos estáveis (🟢)
    ovos_estaveis = 0
    ninhos_estaveis = 0
    for ninho in base_de_ninhos:
        if ninho["risco"] == "🟢":
            ovos_estaveis = ovos_estaveis + ninho["quantidade_ovos"]
            ninhos_estaveis = ninhos_estaveis + 1

    if ninhos_estaveis > 0:
        media_ovos_estaveis = ovos_estaveis / ninhos_estaveis
        print(f"[ 2 ] MÉDIA DE OVOS EM NINHOS ESTÁVEIS (🟢): {int(media_ovos_estaveis)} ovos")
    else:
        print("[ 2 ] MÉDIA DE OVOS EM NINHOS ESTÁVEIS (🟢): Não há ninhos estáveis para calcular.")

    # 3. Ninhos prestes a eclodir
    ninhos_prestes_a_eclodir = 0
    for ninho in base_de_ninhos:
        if ninho["dias_para_eclosao"] <= 5:
            ninhos_prestes_a_eclodir = ninhos_prestes_a_eclodir + 1
    print(f"[ 3 ] NINHOS COM ECLOSÃO PRÓXIMA (<= 5 dias): {ninhos_prestes_a_eclodir}")

    # 4. Região com mais ninhos em risco (🟡)
    contagem_risco_por_regiao = {}
    for ninho in base_de_ninhos:
        if ninho["risco"] == "🟡":
            regiao = ninho["regiao"]
            if regiao in contagem_risco_por_regiao:
                contagem_risco_por_regiao[regiao] = contagem_risco_por_regiao[regiao] + 1
            else:
                contagem_risco_por_regiao[regiao] = 1

    if not contagem_risco_por_regiao:
        print("[ 4 ] REGIÃO COM MAIS NINHOS EM RISCO (🟡): Nenhum ninho classificado como 'ameaçado'.")
    else:
        regiao_mais_risco = ""
        maior_contagem = 0
        for regiao, contagem in contagem_risco_por_regiao.items():
            if contagem > maior_contagem:
                maior_contagem = contagem
                regiao_mais_risco = regiao
        print(f"[ 4 ] REGIÃO COM MAIS NINHOS EM RISCO (🟡): {regiao_mais_risco} ({maior_contagem} ninhos)")

    # 5. Ninhos danificados com predadores
    ninhos_danificados_com_predadores = 0
    for ninho in base_de_ninhos:
        if ninho["status"] == "danificado" and ninho["predadores"] == True:
            ninhos_danificados_com_predadores = ninhos_danificados_com_predadores + 1
    print(f"[ 5 ] NINHOS DANIFICADOS COM PREDADORES: {ninhos_danificados_com_predadores}")

    print("\n" + "="*80)


def adicionar_novo_ninho(base_de_ninhos):
    """Guia o usuário para adicionar um novo registro de ninho, com validação robusta."""
    print("\n" + "-"*80)
    print("||" + " ADICIONAR NOVO REGISTRO DE NINHO ".center(76) + "||")
    print("-"*80)

    # --- Validação da Região ---
    regioes_conhecidas = []
    for ninho in base_de_ninhos:
        if ninho["regiao"] not in regioes_conhecidas:
            regioes_conhecidas.append(ninho["regiao"])

    while True:
        print(f"Regiões conhecidas: {', '.join(regioes_conhecidas)}")
        regiao_input = input("Digite o nome da região: ").strip().title() # Padroniza para ex: "Praia Leste"
        if regiao_input in regioes_conhecidas:
            regiao = regiao_input
            break
        # Permite adicionar nova região, mas pede confirmação
        elif regiao_input:
             confirmacao = input(f"A região '{regiao_input}' é nova. Deseja adicioná-la? (s/n): ").lower().strip()
             if confirmacao == 's':
                 regiao = regiao_input
                 break
        else:
            print("Erro: O nome da região não pode ser vazio.")

    # --- Validação da Quantidade de Ovos ---
    while True:
        ovos_input = input(f"Digite a quantidade de ovos (entre {OVOS_MIN_REALISTA} e {OVOS_MAX_REALISTA}): ").strip()
        is_numeric = True
        if not ovos_input: is_numeric = False
        for char in ovos_input:
            if char not in "0123456789":
                is_numeric = False
                break

        if is_numeric:
            quantidade_ovos = int(ovos_input)
            if OVOS_MIN_REALISTA <= quantidade_ovos <= OVOS_MAX_REALISTA:
                break
            else:
                print(f"Erro: Valor fora dos limites realistas ({OVOS_MIN_REALISTA}-{OVOS_MAX_REALISTA}).")
        else:
            print("Erro: Por favor, digite um número inteiro válido e não negativo.")

    # --- Validação do Status ---
    status_validos = ["intacto", "ameaçado", "danificado"]
    while True:
        status = input(f"Digite o status ({', '.join(status_validos)}): ").lower().strip()
        if status in status_validos:
            break
        else:
            print(f"Erro: Status inválido. Use uma das opções: {', '.join(status_validos)}.")

    # --- Validação do Risco ---
    riscos_validos = ["🟢", "🟡", "🔴"]
    while True:
        risco = input(f"Digite o risco (símbolos permitidos: {', '.join(riscos_validos)}): ").strip()
        if risco in riscos_validos:
            break
        else:
            print(f"Erro: Risco inválido. Utilize um dos símbolos: {', '.join(riscos_validos)}.")

    # --- Validação dos Dias para Eclosão ---
    while True:
        dias_input = input(f"Digite os dias para eclosão (entre {DIAS_ECLOSAO_MIN} e {DIAS_ECLOSAO_MAX}): ").strip()
        is_numeric = True
        if not dias_input: is_numeric = False
        for char in dias_input:
            if char not in "0123456789":
                is_numeric = False
                break

        if is_numeric:
            dias_para_eclosao = int(dias_input)
            if DIAS_ECLOSAO_MIN <= dias_para_eclosao <= DIAS_ECLOSAO_MAX:
                break
            else:
                print(f"Erro: Valor fora dos limites realistas ({DIAS_ECLOSAO_MIN}-{DIAS_ECLOSAO_MAX}).")
        else:
            print("Erro: Por favor, digite um número inteiro válido e não negativo.")

    # --- Validação da Presença de Predadores ---
    while True:
        predadores_input = input("Há presença de predadores? (s/n): ").lower().strip()
        if predadores_input == 's':
            predadores = True
            break
        elif predadores_input == 'n':
            predadores = False
            break
        else:
            print("Erro: Resposta inválida. Digite 's' para sim ou 'n' para não.")

    # --- Criação e Adição do Novo Ninho ---
    novo_ninho = {
        "regiao": regiao,
        "quantidade_ovos": quantidade_ovos,
        "status": status,
        "risco": risco,
        "dias_para_eclosao": dias_para_eclosao,
        "predadores": predadores
    }

    base_de_ninhos.append(novo_ninho)
    print("\n---> Sucesso! Novo ninho registrado na base de dados. <---\n")
    print("-"*80)


# -----------------------------------------------------------------------------
# FASE 3: INTERFACE PRINCIPAL DO SISTEMA (LOOP DE EXECUÇÃO)
# -----------------------------------------------------------------------------

def iniciar_sistema():
    """Função principal que inicia o loop do sistema interativo."""
    while True:
        print("\n" + "*"*80)
        print("*" + " SISTEMA DE MONITORAMENTO: GUARDIÃO DAS TARTARUGUINHAS ".center(78) + "*")
        print("*"*80)
        print("\nMENU DE OPÇÕES:")
        print("  1. Visualizar Relatório Completo de Ninhos")
        print("  2. Consultar Estatísticas de Monitoramento")
        print("  3. Adicionar Novo Registro de Ninho")
        print("  4. Sair do Sistema")

        escolha = input("\n>> Digite o número da opção desejada: ").strip()

        if escolha == '1':
            exibir_relatorio_completo(ninhos)
        elif escolha == '2':
            calcular_estatisticas(ninhos)
        elif escolha == '3':
            adicionar_novo_ninho(ninhos)
        elif escolha == '4':
            print("\nEncerrando o sistema... Obrigado por proteger nossas tartarugas!\n")
            break
        else:
            print("\n[ERRO] Opção inválida. Por favor, escolha um número de 1 a 4.")

# -----------------------------------------------------------------------------
# INICIALIZAÇÃO DO PROGRAMA
# -----------------------------------------------------------------------------
iniciar_sistema()